apiVersion: v1
kind: Pod
metadata:
  name: first-pod-name
  labels:
    app: first-pod-app
spec:
  containers:
    - name: first-pod-container
      image: nginx:stable-alpine
      ports: 
      - containerPort: 80
